config/routes.rb
Techtalentstore::Application.routes.draw do
  

  get "orders/index"
  get "store/index"
  post "store/add_to_cart"
  delete "store/remove_from_cart"
  get "description" => "store#description", as: :product_description
  get "cart" => "customers#cart", as: :cart
  
  root 'store#index'

  devise_for :users
  resources :products
  resources :customers

end

app/models/store.rb
class Store < ActiveRecord::Base

	has_one :order

end

app/controllers/store_controller.rb
class StoreController < ApplicationController

	#this will be our home/landing page
	#it will display all the products
	def index
		#we want to display the products that have a buyable quantity
		#(i.e., more than zero!), and display them in alphabetical order.
		@products = Product.where('quantity > 0').order(:name)

    if session[:cart].nil?
      session[:cart] = {}
    end
    @cart = session[:cart]

    @sum = Cart.sum_total(@cart)
	end

	def description
		#with this action we'll pull up a page similar to the product_show page.
		#you'll be passing a parameter to call up the specific product,
		#as seen below.
		@product = Product.find(params[:id])
	end

	def add_to_cart
		product_id = params[:product_id].to_i
  	quantity = params[:quantity].to_i
    @product_name = params[:product_name]
    price = params[:price].to_f

  	line_item = { product_id: product_id, quantity: quantity}
  	
  	if session[:cart].nil?
  		session[:cart] = {}
  	end

		current_cart = session[:cart]
  	
  	if current_cart[product_id].nil?
  		current_cart[product_id] = [quantity, @product_name, price]
  	else
  		value_array = current_cart[product_id]
      old_quantity = value_array[0]
      new_quantity = old_quantity + quantity
  		current_cart[product_id] = [new_quantity, @product_name, price]
      #the current_cart is a has, where the product_id is key, and an array, #which contains the quantity desired, the product name, and the price #per unit, is the value
  	end

  	@cart = current_cart

  	#Rails.logger.info "CART= #{session[:cart]}"

    @sum = Cart.sum_total(@cart)
	end

	def remove_from_cart
    product_id = params[:product_id].to_i
    @cart = session[:cart]
    @cart.delete(product_id)

    redirect_to store_index_path
	end
end

app/views/store/_cart.html.erb
<% if @cart.count <= 0 %>
	Your cart is empty.
<% else %>
	You have <%= pluralize(@cart.count, "item") %> in your cart. <br />
	<button id="toggle_cart_button">View</button>
	<div id="cart_detail_panel">
		<% @cart.each do |key, value| %>
			<div>
				<%= value [0] %> <%= value[1] %> @ <%= number_to_currency(value[2]) %> 
				<%= link_to "x", store_remove_from_cart_path(:product_id => key), :method => :delete, :class => "delete-from-cart-button" %>
			</div>
		<% end %>
		<hr width="20%" align="left" />
		<div id="cart_total">
			Total: <%= number_to_currency(@sum) %>
			<%= link_to "Place Order", new_customer_path %>
		</div>
	</div>
<% end %>

app/views/store/_cartcount.html.erb
<% if @cart.count <= 0 %>
	<%= link_to image_tag('emptycart.png', width:"50", height:"50"), cart_path %>
<% else %>
	<div class="cartstyle">
		<%= link_to @cart.count, cart_path %>
	</div>
<% end %>

app/views/store/add_to_cart.js.erb
alert('Thank you for choosing <%= @product_name %>');


$('#cart_msg').html('<%= escape_javascript(render "cart") %>');

$('#cart_count').html('<%= escape_javascript(render "cartcount") %>');

app/views/store/description.html.erb
<div>

  <p>
    <%= @product.name %>
  </p>

  <p>
    <strong>Unit Price:</strong>
    <%= number_to_currency(@product.unit_price, :unit => "$") %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= @product.quantity %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= @product.brand %>
  </p>

  <p>
    <strong>Model Number:</strong>
    <%= @product.model_num %>
  </p>

  <%= link_to 'Back to Storefront', root_path %>
</div>

app/views/store/index.html.erb
<div>
	<div id="cart_count">
		<%= render 'cartcount' %>
	</div>
	<div id="cart_msg">
		<%= render 'cart' %>
	</div>
	<div>
		<% @products.each do  |product| %>
			<div class="product-bubble">
				<strong><%= product.name %></strong><br />
				<%= number_to_currency(product.unit_price, :unit => "$") %><br />
				<%= link_to "Click for Description", product_description_path(:id => product.id) %><br />
				<div>
					<!-- A field to put how many of the item you want to buy. -->
					<input type="text" class="quantity" placeholder="Enter Qty." size="7" /><br />
					<!-- Below is the submit button for the above text field -->
					<button class="add-to-cart-button" 
					data-product-id="<%= product.id %>" 
					data-product-name="<%= product.name %>"
					data-price="<%= product.unit_price %>"
					id="button">Add to Cart</button>
					<!-- Check out 'store.js' for the functionality of this all -->
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/store/remove_from_cart.js.erb
alert('You don\'t want it? YOU DON\'T GET IT!');

$('#delete_msg').html('<%= escape_javascript(render "cart") %>');